/*!
 *
 * This file is part of the nginx-fancyindex-flat-theme, licensed under the GNU
 * General Public License. See the LICENSE file for details.
 *
 * Copyright (C)
 *  2018 Alexander Haase <ahaase@alexhaase.de>
 */
function generateList(){var e=document.getElementById("list");e.removeAttribute("cellpadding"),e.removeAttribute("cellspacing"),e.classList.add("table","table-sm","table-hover","text-nowrap"),e.tHead.children[0].classList.add("d-none","d-md-table-row"),"/"!=window.location.pathname&&e.deleteRow(1);for(var a,s=0;a=e.rows[s];s++)filetype=function(e){if(e.endsWith("/"))return"folder";switch(e.split(".").pop().toLowerCase()){case"txt":return"text";case"pdf":return"pdf";case"bmp":case"gif":case"jpeg":case"jpg":case"png":case"tif":case"tiff":return"image";case"aac":case"aiff":case"m4a":case"mp3":case"ogg":case"opus":case"wav":return"audio";case"amv":case"avi":case"flv":case"m4v":case"mkv":case"mov":case"mp4":case"m4p":case"mpeg":case"mpg":case"ogv":case"vob":case"webm":case"wmv":return"video";case"7z":case"a":case"apk":case"ar":case"bin":case"bz2":case"cab":case"dmg":case"gz":case"iso":case"jar":case"lz":case"lzma":case"lzo":case"pak":case"partimg":case"rar":case"s7z":case"tar":case"tbz2":case"tgz":case"tlz":case"txz":case"xz":case"zip":return"archive";case"doc":case"docx":case"odt":case"rtf":return"word";case"csv":case"ods":case"xls":case"xlsx":return"excel";case"odp":case"ppt":case"pptx":return"powerpoint";case"c":case"class":case"cpp":case"cs":case"h":case"hpp":case"hxx":case"java":case"py":case"sh":case"swift":case"vb":return"code"}}(a.cells[0].children[0].innerHTML),a.insertCell(0).innerHTML=0<s?'<i class="fa fa-fw '+function(e){switch(e){case"folder":return"fa-folder";case"archive":case"audio":case"code":case"excel":case"image":case"pdf":case"powerpoint":case"text":case"video":case"word":return"fa-file-"+e+"-o";default:return"fa-file-o"}}(filetype)+'" aria-hidden="true"></i>':"",a.cells[0].classList.add("col-auto"),a.cells[1].classList.add("col","filename"),a.cells[2].classList.add("col-auto","d-none","d-md-table-cell"),a.cells[3].classList.add("col-auto","d-none","d-md-table-cell"),"image"==filetype&&a.cells[1].children[0].setAttribute("data-lightbox","roadtrip")}
